[package]
name = "wslgit"
version = "0.8.0"
authors = ["Andreas Riffnaller-Schiefer <andreas.schiefer@gmail.com>"]
license = "MIT"

[dependencies]
regex = "1"
lazy_static = "1.3"

[dev-dependencies]
assert_cli = "0.6"
