[package]
name = "wslgit"
version = "1.3.0"
authors = ["Andreas Riffnaller-Schiefer <andreas.schiefer@gmail.com>"]
license = "MIT"

[dependencies]
regex = "1.7.0"
lazy_static = "1.4"

[dev-dependencies]
assert_cmd = "2.0.7"
predicates = "2.1.5"

[profile.release]
strip = true
